services:
  money-transfer-api:
    image: money-transfer-api
    container_name: money-transfer-api
    build:
      context: ../
      dockerfile: ./infrastructure/Dockerfile
    ports:
      - 8082:8080
    depends_on:
      - money-transfer-postgres
  money-transfer-postgres:
    image: postgres:15.14-alpine3.21
    container_name: money-transfer-postgres
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=5432
      - POSTGRES_USER=postgres
      - POSTGRES_DB=MoneyTransfer
    volumes:
      - postgres-money-transfer-data:/var/lib/postgresql/data
volumes:
  postgres-money-transfer-data:
